# Generated by Django 3.1.1 on 2020-09-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=30, verbose_name='имя')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=30, verbose_name='фамилия')),
                ('age', models.IntegerField(help_text='Введите возраст', max_length=3, verbose_name='возраст')),
                ('active', models.BooleanField(default=True, help_text='Активен ли', verbose_name='активность')),
                ('languages', models.CharField(blank=True, choices=[('RU', 'Русский'), ('EN', 'Английский'), ('UA', 'Украинский'), ('PO', 'Португальский')], max_length=2, null=True, verbose_name='языки')),
            ],
        ),
    ]
