# Generated by Django 3.1.1 on 2020-09-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200910_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(help_text='Введите имя', max_length=30, verbose_name='имя'),
        ),
    ]
