# Generated by Django 3.1.1 on 2020-09-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_person_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Загрузите фото', null=True, upload_to='media', verbose_name='аватар'),
        ),
    ]
