# Generated by Django 3.1.1 on 2020-09-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200910_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Загрузите фото', null=True, upload_to='images', verbose_name='аватар'),
        ),
    ]
